### ISSUE TITLE
About paper reproduction problem

### ISSUE THREAD

**Issue by Stonebobo** [kuihua/MSPFN#3]
Hello, I want to ask a question. The model I trained before loading in the training set does not have problems, but loading the trained model in the test set will report an error:
Traceback (most recent call last):
  File "E:/bwl_python/MSPFN-me-7.3/model/test/test_MSPFN.py", line 51, in <module>
    saver.restore(sess, '../MSPFN/epoch6')
  File "E:\anaconda\path\envs\bwltfgpu\lib\site-packages\tensorflow\python\training\saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key generator/BCM2_0/down2_1/alpha not found in checkpoint
	 [[node save/RestoreV2 (defined at /bwl_python/MSPFN-me-7.3/model/test/test_MSPFN.py:50) ]]
	 [[save/RestoreV2/_453]]
  (1) Not found: Key generator/BCM2_0/down2_1/alpha not found in checkpoint
	 [[node save/RestoreV2 (defined at /bwl_python/MSPFN-me-7.3/model/test/test_MSPFN.py:50) ]]
0 successful operations.
0 derived errors ignored.

In addition, what is the specific version of your tensorflow? 1.1? 1.14? (Ps, I have some version errors when using 1.1),

 looking forward to your reply, thank you!

**Comment by kuihua** [comment]
Q1: The tensorflow version, the memory space, or the graph will cause this problem. You can solve this problem by referring to https://blog.csdn.net/u010327061/article/details/84078583.
Q2: The version of the tensorflow is 1.12 with cuda 9.0.
Q3: How much training samples do you adopt and how to set the learning rate?

**Comment by Stonebobo** [comment]
Tank you for your reply.
The number of my training set is 3600(481*321) from Rain100L_new_version of CVPR 2017 
the learning rate has not changed, the original value in your code is used--start_learning_rate = 5e-4#
Q3 may be caused by the data set is too small than you paper used.
thank you!I will try again about Q1.
